### ISSUE TITLE
Certain videos are wrongly not played when loaded in the sidebar

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/side-view#141]
[Affected versions]:
- Firefox 59.0.2 and up
- Side View 0.2.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a clean Firefox profile with the latest Side View 0.2.0 installed.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites.
2. Navigate to https://vimeo.com/ and click a video thumbnail.
3. Click the "Open current tab in sidebar" toolbar button.
4. Play the video inside the sidebar.

[Expected result]:
- The video starts.

[Actual result]:
- The video is displayed as an image and it cannot be played.

[Notes]:
- I've encountered this behavior on several websites such as: http://www.metacafe.com/, https://archive.org, https://myspace.com, https://www.ted.com/talks .
- For some websites, the following message appeared: "No video with supported format and MIME type found".
- Here is a screen recording with  the issue:
![side view - video content](https://user-images.githubusercontent.com/31244235/38357867-6ceb96fe-38cc-11e8-8df6-e30d05b875e5.gif)

**Comment by fzzzy** [comment]
this seems fixed with the new 0.3 panel implementation.

**Comment by Softvision-CristinaBadescu** [comment]
I can still reproduce this issue on "http://www.metacafe.com/" and "https://myspace.com/discover/videos", using the latest Side View v0.3.2 (custom built on 2018-04-13), on latest Nightly build 61.0a1 (2018-04-13), on Windows 10 x64, Mac 10.13.4 and Arch Linux 4.12. When I try to open the videos in the sidebar, the "No video with supported format and MIME type found" message is displayed.

However, this issue is no longer reproducible on https://vimeo.com, https://archive.org, and https://www.ted.com/talks .

Considering this, I'm going to reopen the issue.

**Comment by johngruen** [comment]
Yeah, seeing a mimetype error on metacafe

**Comment by johngruen** [comment]
This doesn't block launch

**Comment by Softvision-CristinaBadescu** [comment]
This issue is no longer reproducible using the latest Side View v0.3.2, on latest Nightly build 61.0a1 (2018-04-26), on Windows 10 x64, Mac 10.13.4 and Ubuntu 14.04 x64. The websites are opened by default to their desktop version.
